services:
  with_alex_doctrine_audit.user_provider:
    class: WithAlex\DoctrineAuditBundle\User\TokenStorageUserProvider
    arguments: ["@security.helper"]
    public: true

  with_alex_doctrine_audit.configuration:
    class: WithAlex\DoctrineAuditBundle\AuditConfiguration
    arguments: ["%with_alex_doctrine_audit.configuration%"]
    public: true

  WithAlex\DoctrineAuditBundle\AuditConfiguration:
    alias: with_alex_doctrine_audit.configuration
    public: true

  with_alex_doctrine_audit.reader:
    class: WithAlex\DoctrineAuditBundle\AuditReader
    arguments: ["@with_alex_doctrine_audit.configuration", "@doctrine.orm.default_entity_manager"]
    public: true

  WithAlex\DoctrineAuditBundle\AuditReader:
    alias: with_alex_doctrine_audit.reader
    public: true

  with_alex_doctrine_audit.event_subscriber.audit:
    class: WithAlex\DoctrineAuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@with_alex_doctrine_audit.configuration", , "@with_alex_doctrine_audit.user_provider", "@request_stack"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  with_alex_doctrine_audit.event_subscriber.create_schema:
    class: WithAlex\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
    arguments: ["@with_alex_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  with_alex_doctrine_audit.twig_extension:
    class: WithAlex\DoctrineAuditBundle\Twig\Extension\TwigExtension
    arguments: ['@doctrine']
    tags:
      - { name: twig.extension }

  WithAlex\DoctrineAuditBundle\Command\CleanAuditLogsCommand:
    tags:
      - { name: 'console.command', command: 'audit:clean' }
